### ISSUE TITLE
Documentation: Insert API route to user authentication

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1399]
The endpoint `/tokens` is not present on our current API documentation (https://getorb.io/api/fleet.html)

This endpoint is very important to use the rest of the API endpoints, since all others require authentication.

We need to insert it, already considering the new authentication using bearer token.

**Comment by mclcavalcante** [comment]
We need to add one more statement pointing to mainflux's /token endpoint here:
https://github.com/ns1labs/orb-website/blob/main/.github/workflows/ci.yml

```
 - name: redoc-cli user-token
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle path/to/mainflux/users/openapi -o docs/api/token.html'
```
