### ISSUE TITLE
Agents: when agent is provisioned through config file without auto_provision with agent tags which matches existent groups, the agent fails to subscribe to the groups

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1756]
Steps to reproduce:

- Create an agent on orb without any orb tags
- Create a group on orb (in this example the group has tag `test:policy`)
- Provision the agent using a config file using agent tags that matches the group:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/0054d165-405b-4adc-ad44-d35db5c183d7)

Your config file must be like this and you must save it as `agent.yaml` on orb root path (you can change it, must will need to make the necessary adaptations):

**important: put your network on `iface: eth0` if you are not using eth0.

```
orb:
  backends:
    pktvisor:
      api_port: '46545'
      binary: /usr/local/sbin/pktvisord
      config_file: /usr/local/orb/agent.yaml
  cloud:
    api:
      address: https://stg.orb.live
    mqtt:
      address: tls://stg.orb.live:8883
      id: "f2ff2f13-0bce-4364-b66b-a45dbd25b5ca"
      key: "7e0fd8c3-95dc-4c71-8bb4-67efd6ed43f5"
      channel_id: "4154c5bc-725e-4ce1-9ea4-95f2230f45aa"
  tags:
      test: policy
  tls:
    verify: true
version: '1.0'
visor:
  taps:
    default_pcap:
      config:
        iface: eth0
      input_type: pcap
```

Use this command to provision your agent:

`docker run -d -v /<path_to_orb>/orb:/usr/local/orb --net=host ns1labs/orb-agent:develop run -c /usr/local/orb/agent.yaml`

Expected behavior:

- Agent must be online and subscribed to the group created previously
- Check thread and fix suggestion: 
-- https://ns1labs.slack.com/archives/C01UNG6UK37/p1662573661293519?thread_ts=1662573347.256709&cid=C01UNG6UK37

Current behavior:

- Agent fails to connect to subscribe to groups

Full logs:

[https://app.zenhub.com/files/340174841/574dc21d-7bb2-494a-8cba-640997828636/download](https://app.zenhub.com/files/340174841/574dc21d-7bb2-494a-8cba-640997828636/download)
