### ISSUE TITLE
Agents: debug logs not working properly on configuration files

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1782]
When an agent is provisioned via configuration files, one option is to run this agent in a debug mode. So, the configuration must be set as:

```
orb:
  debug:
    enable: true
```

When it is true, the user must be able to see DEBUG logs, but currently it is not working as expected. Even with this configuration enabled, the logs of the agent are only the usual ones (without debug).

Full logs of an agent provisioned via config file with debug enabled:

[https://app.zenhub.com/files/340174841/ecedf372-cc38-4e3c-bd3b-41bda441e9b9/download](https://app.zenhub.com/files/340174841/ecedf372-cc38-4e3c-bd3b-41bda441e9b9/download)

File used:

```
version: "1.0"

# this section is used by pktvisor
# see https://github.com/ns1labs/pktvisor/blob/develop/RFCs/2021-04-16-75-taps.md
visor:
  taps:
    default_pcap:
      input_type: pcap
      config:
        iface: wlo1
      tags:
        key1: value1
        key2: value2

# this section is used orb-agent
# most sections and keys are optional
orb:
#  # these are arbitrary key value pairs used for organization in the control plane and UI
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
      config_file: "/usr/local/orb/agent.yaml"
      api_port: "10855"
  tags:
    test: test
  tls:
    verify: true
  cloud:
    config:
      # optionally specify an agent name to use during auto provisioning
      # hostname will be used if it's not specified here
      agent_name: agent-prod-config-file-1
      auto_provision: true

    api:
      address: https://stg.orb.live
      # if auto provisioning, specify API token here (or pass on the command line)
      token: token
    mqtt:
      address: tls://stg.orb.live:8883
#      # if not auto provisioning, specify agent connection details here
#      id: "b9b4d61f-5847-4ab1-b266-1b1008f577a4"
#      key: "32cfddeb-6e98-45d6-8867-f75143c00475"
#      channel_id: "c366b823-87df-4c7b-af64-c9c99c13a73b"
  debug:
    enable: true
```

Full logs of an agent provisioned via config file with debug disabled:

[https://app.zenhub.com/files/340174841/0d23b06d-6fe1-4b4d-8634-5f4e8f5b81ab/download](https://app.zenhub.com/files/340174841/0d23b06d-6fe1-4b4d-8634-5f4e8f5b81ab/download)

File used:

```
version: "1.0"

# this section is used by pktvisor
# see https://github.com/ns1labs/pktvisor/blob/develop/RFCs/2021-04-16-75-taps.md
visor:
  taps:
    default_pcap:
      input_type: pcap
      config:
        iface: wlo1
      tags:
        key1: value1
        key2: value2

# this section is used orb-agent
# most sections and keys are optional
orb:
#  # these are arbitrary key value pairs used for organization in the control plane and UI
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
      config_file: "/usr/local/orb/agent.yaml"
      api_port: "10856"
  tags:
    test: test
  tls:
    verify: true
  cloud:
    config:
      # optionally specify an agent name to use during auto provisioning
      # hostname will be used if it's not specified here
      agent_name: agent-prod-config-file-2
      auto_provision: true

    api:
      address: https://stg.orb.live
      # if auto provisioning, specify API token here (or pass on the command line)
      token: token
    mqtt:
      address: tls://stg.orb.live:8883
#      # if not auto provisioning, specify agent connection details here
#      id: "b9b4d61f-5847-4ab1-b266-1b1008f577a4"
#      key: "32cfddeb-6e98-45d6-8867-f75143c00475"
#      channel_id: "c366b823-87df-4c7b-af64-c9c99c13a73b"
```

command:

```
docker run -d -v /orb:/usr/local/orb --net=host ns1labs/orb-agent:develop run -c /usr/local/orb/agent.yaml
```

Expected behavior:

- When the config

```
  debug:
    enable: true
```
is set on the configuration file, the DEBUG logs must be activated on the agent provisioned.
