### ISSUE TITLE
Agents: when an agent configuration file overwrites the default file, pktvisor is not generated by the specified file

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1987]
When I overwrite the default file (/opt/orb/agent.yaml) even if I pass the path of the file that is for pktivsor to consume (orb.backends.pktvisor.config_file) it will not be used, the default one will be used and the user has no way to know that but seeing that the data (taps, for example) is not correct (and it is not related to Everton's PR.. it is true to old agents)
(This ONLY happens if I overwrite the default file and don't pass run -c /path/to/default.yaml. If I pass, it will work fine.)

Steps to reproduce:

create a orb-agent.yaml like this:

```
orb:
  backends:
    pktvisor:
      api_port: "10857"
      binary: /usr/local/sbin/pktvisord
      config_file: /opt/orb/agent.yaml
  cloud:
    api:
      address: https://stg.orb.live
    config:
      auto_provision: false
    mqtt:
      address: tls://stg.orb.live:8883
  tags:
      test: policy
  tls:
    verify: true
version: '1.0'
visor:
  taps:
    my_pcap:
      config:
        iface: wlo1
      input_type: pcap
    my_flow:
      input_type: flow
      config:
        flow_type: "sflow"
        bind: "0.0.0.0"
        port: 9995
```

provide the agent using:

```
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=blabla \
-e ORB_CLOUD_MQTT_CHANNEL_ID=blabla \
-e ORB_CLOUD_MQTT_KEY=blabla \
-v ${PWD}/orb-agent.yaml:/opt/orb/agent.yaml \
ns1labs/orb-agent:develop
```

Check the agent taps (pktvisor configuration).

Expected behavior:

- Taps defined on pktvisor config file must be on agent's backend

Current behavior:

- Pktvisor will create the default one
