### ISSUE TITLE
Evaluate Orb agent fix to address MacOS networking issue

### ISSUE THREAD

**Issue by rboucher-me** [orb-community/orb#2045]
To address an issue with Docker networking on MacOS, pktvisor needs to bind to `0.0.0.0` instead of the default `localhost` to allow querying the pktvisor API from _outside_ the Orb agent container. This can be set in the Orb agent configuration file:
```
orb:
  backends:
    pktvisor:
      binary: /usr/local/sbin/pktvisord
      config_file: /opt/orb/agent.yaml
      api_host: 0.0.0.0
```

This ticket is to investigate if this could be made the default value in Orb (does it break it on other platforms?) and what might be the consequences of doing this.
