### ISSUE TITLE
When a agent tap is defined without any config predefined taps route fails

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#2050]
When a agent connect to control plane without any config predefined on taps the taps route `/api/v1/agents/backends/pktvisor/taps` fails.

Steps to reproduce:

- Use an agent.yaml with following taps for pktvisor:

```
visor:
  taps:
    default_something:
      input_type: something
```

Example:

```
version: '1.0'
orb:
  backends:
    pktvisor:
      binary: /usr/local/sbin/pktvisord
      config_file: /opt/orb/agent.yaml
  tags:
    two: tags
visor:
  taps:
    default_netprobe:
      input_type: netprobe
      tags:
        virtual: true
```

- Run the agent..
 Example of provisioning command:

```
docker run -d --restart=always --net=host \
-e ORB_CLOUD_ADDRESS=orb.live \
-e ORB_CLOUD_MQTT_ID=a9a87e39-f7e9-42ea-b4e0-2ef40a71de50 \
-e ORB_CLOUD_MQTT_CHANNEL_ID=11b4e7a1-f1f5-4763-961b-8ad201cc7f8e \
-e ORB_CLOUD_MQTT_KEY=51ee671f-044d-473f-80cd-fa3aedc29b50 \
-e PKTVISOR_PCAP_IFACE_DEFAULT=auto \
-v ${PWD}/agent.yaml:/opt/orb/agent.yaml \
ns1labs/orb-agent:develop
```

- Make a get request to taps route: `/api/v1/agents/backends/pktvisor/taps`

Expected behavior:
- Existent taps must be displayed

Current behavior:
- Request fails with status code 500 and message `Error to group taps`

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/26efa7ee-e152-44cf-b539-299ff5e0ef8c)

You can also check this error trying to create a new policy:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/e2050aac-0c5f-49f2-979f-395e363c269e)

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/91e99f82-21e2-4634-9c71-0ee95258d027)
