### ISSUE TITLE
agent with null taps when config file is given to orb-agent docker without pktvisor config_file path

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#949]
When an agent is provisioned through configuration file, if file path is not set, agent goes up with null tap.

![image](https://user-images.githubusercontent.com/78241475/190509114-ea4502d3-e0ce-445f-a410-9a8543f4dfab.png)

Logs:

[_epic_davinci_logs.txt](https://github.com/ns1labs/orb/files/9579082/_epic_davinci_logs.txt)

```
  backends:
    pktvisor:
      config_file: "/usr/local/orb/agent.yaml"
```

Once that this path is inserted on command line, the file should be correctly found and used:

```
docker run -v my_local/orb:/usr/local/orb/ --net=host ns1labs/orb-agent:develop run -c /usr/local/orb/agent.yaml
```

File used:

```
visor:
  taps:
    default_pcap:
      input_type: pcap
      config:
        iface: wlo1
      tags:
        key1: value1
        key2: value2

# this section is used orb-agent
# most sections and keys are optional
orb:
#  # these are arbitrary key value pairs used for organization in the control plane and UI
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
      api_port: "10855"
  tags:
    test: test
  tls:
    verify: true
  cloud:
    config:
      # optionally specify an agent name to use during auto provisioning
      # hostname will be used if it's not specified here
      agent_name: agent-prod-config-file
      auto_provision: true

    api:
      address: https://stg.orb.live
      # if auto provisioning, specify API token here (or pass on the command line)
      token: token
    mqtt:
      address: tls://stg.orb.live:8883
```
